"""Data schemas for expense approval, risk analysis, and audit outcomes."""

from __future__ import annotations

from typing import Literal
from pydantic import BaseModel, Field


class Expense(BaseModel):
    """Normalized corporate expense report."""

    amount: float = Field(..., description="Expense amount in USD")
    submitter: str = Field(..., description="Identifier/email of the submitter")
    category: str = Field(..., description="Expense category (e.g., Travel, Meals, Software, Supplies)")
    description: str = Field(..., description="Business purpose or item description")
    date: str = Field(..., description="Expense transaction date (YYYY-MM-DD)")
    redacted_categories: list[str] = Field(
        default_factory=list,
        description="Categories of PII redacted from the description (e.g. SSN, CREDIT_CARD)",
    )
    is_security_event: bool = Field(
        default=False,
        description="Indicates whether this expense triggered a security checkpoint flag",
    )


class RiskAssessment(BaseModel):
    """Structured risk review output generated by the LLM or security checkpoint."""

    risk_level: Literal["LOW", "MEDIUM", "HIGH"] = Field(
        ..., description="Overall risk rating of the expense"
    )
    risk_factors: list[str] = Field(
        default_factory=list,
        description="Key risk factors, anomalies, or policy flags detected",
    )
    alert_summary: str = Field(
        ..., description="Concise alert summary explaining the rationale to the approver"
    )
    recommended_action: Literal["APPROVE", "REJECT", "REQUEST_MORE_INFO"] = Field(
        ..., description="Suggested decision for the human approver"
    )
    is_security_event: bool = Field(
        default=False,
        description="Flagged as a security incident (e.g. prompt injection attempt)",
    )


class ExpenseReview(BaseModel):
    """Container pairing an expense with its automated risk or security assessment."""

    expense: Expense
    risk_assessment: RiskAssessment


class ExpenseOutcome(BaseModel):
    """Final decision record for an expense."""

    expense: Expense
    status: Literal["APPROVED", "REJECTED"]
    reason: str
    reviewed_by: Literal["auto_approval_rule", "human_approver"]
    risk_alert: RiskAssessment | None = None
    approver_notes: str | None = None
    is_security_event: bool = False
